server:
  port: 8012 # 服务端口
  contextPath: /stockservice

debug: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ # 服务注册中心地址
  instance:
    preferIpAddress: true

spring:
  application:
    name: stock-service # 服务名称
  datasource:
    dbcp2.validation-query: select 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/stockdb?stringtype=unspecified
    name: orderdb
    username: pgdbo
    password: sql


mybatis.configuration:
  map-underscore-to-camel-case: true
  default-fetch-size: 100
  default-statement-timeout: 30

logging:
  file: ./target/app.log
  level:
    org.springframework: INFO
    cn.devmgr: TRACE

  
# To disable/enable Spring Security 
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: rs1
      clientSecret: secret
      #accessTokenUri: http://localhost:8009/auth/oauth/token
      #userAuthorizationUri: http://localhost:8009/auth/oauth/authorize
    resource:
      jwt:
        keyValue: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkCoBhnUW7gCyBE62ic3h
            qhNNrERokyG6gEPXL6fX93yWhfr5h4mWjKT2SOgoryAt8snctlExridfNQA5DohX
            9kCH7XBO1o4W2TCiZmva25mfoqU0Qz6zTZQXAPPfbCr1WrsCLY4wloAcCh7t/39S
            G3Q1v8GBf5ZrM1hXfDZgRakCXfB910OHbCvXAnFg0GLWWLG1uag6axCBXpCNOGHs
            H7L2fa+f7VapxXbY7uGYkGFkaTDQkjLHpjF7aZDc07uiREQGJxT19th6fz8hW8Cs
            Q2FVuBfH9g8V8qB5QmT2r8O9HGpLbyWOdw4ewAd8ki9pHHg69L6vZrLPPPx8fWiY
            vQIDAQAB
            -----END PUBLIC KEY-----

